<a href="https://colab.research.google.com/github/phamtantai-hcm/BaiTap_Python/blob/main/24_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np
arr_np = np.arange(10)
print(arr_np)
print(arr_np.shape)
print('-----------------------')
arr_tf = tf.convert_to_tensor(arr_np)
print(arr_tf)
print(arr_tf.shape)
print('-----------------------')
arr_np_back = arr_tf.numpy()
print(arr_np_back)
print(arr_np_back.shape)
print('-----------------------')

[0 1 2 3 4 5 6 7 8 9]
(10,)
-----------------------
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64)
(10,)
-----------------------
[0 1 2 3 4 5 6 7 8 9]
(10,)
-----------------------


In [3]:
import numpy as np
l = list(range(1,4))
data = np.array(l)

print(data)
print(data[0])
print(data[1])

[1 2 3]
1
2


In [4]:
import numpy as np
list1D = [1,2,3]
data = np.array(list1D)

print(data)
print(data.shape)

[1 2 3]
(3,)


In [6]:
import numpy as np
list2D = [[1,2,],[3,4],[5,6]]
data = np.array(list2D)

print(data)
print(data.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
